# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '02_ObservableCreate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
pod 'RxSwift'
  use_frameworks!

  # Pods for 02_ObservableCreate

end
