# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '03_Subject' do
pod 'RxSwift'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 03_Subject

end
